### PR TITLE
Source specific filtering

### PR DESCRIPTION
**Pull request by kyokley**
I thought it might be useful to be able to define filters specific to a source when using a file. For each line in the file, I split on whitespace, taking the first entry as the source and everything that follows as regexes to be applied to that source. I didn't make any changes to OPML file handling.

Either way, this is a nifty script so thank you for sharing it.

### CODE REVIEW

**Comment by p-e-w** [comment]
Thank you for your interest!

I have considered implementing source-specific filters from the start and I really like the idea of having them be part of the source file. Unfortunately, the proposed implementation breaks some things in its current state. Note that `_read_file` is also used for loading the filters file, in which case a `list`, not `dict`, is expected, so this simply throws an error if a filters file is loaded (an option I definitely want to keep, as it's certainly the more common use case).

The parsing of source lines into source + filters should therefore happen after loading the lines from the file. This has the additional advantage that sources passed inline with `-s` can be processed as well, allowing per-source specifications on the command line.

Another enhancement that I've been pondering for a while is allowing users to combine filters with **AND** in addition to the current **OR**. People might want to filter out items containing both _NASA_ and _Pluto_ in whatever order and no matter how far apart. My idea was to split filter strings on a delimiter and assume all items to be linked by **AND**, while retaining the **OR** linking between filter lines, which should allow for very flexible specifications (though not arbitrary Boolean operations). The delimiter to be used is a crucial decision. I feel that using space as a delimiter might not be optimal, as it's very common to have a filter like "new horizons", which by your code would be considered two filters unless the space is escaped somehow (e.g. by replacing it with its Unicode code point). Space definitely _should_ be used to separate the URL from the filter list, because it is just about the only character that cannot be part of a URL. ~~For the list itself, how about using commas `,` to link filters with **AND** and semicolons `;` for **OR** (the role taken by line breaks in the filters file)? We could then also have commas as **AND** separators in the filters file and provide much more powerful filtering everywhere.~~

**Update:** Scratch the above. I just realized that commas are used in regexes like `.{1,3}`. Is this a problem or are such regexes useless as real-world text filters anyway?

**Comment by kyokley** [comment]
I completely forgot about checking filters in a file. Sorry about that. I can fix it but I'm not quite following how you would manage to specify a source-specific filter from the command line. Do you think you can give me an example invocation?

As for supporting **AND**-ing or **OR**-ing, I think it can be done but it will take away from the simplicity of the program. As you mentioned, using `,` or `;` as delimiters may not be good choices but, more importantly, using any delimiter to represent **AND** and a different one to represent **OR** will basically force you into building some complicated parsing.

For the sake of argument, let's assume `,` represents **AND** and `;` represents **OR**. For simple filters like A **AND** B, there's no problem:

```
A,B
```

However, I think things become confusing when a third pattern is included. Something like A **AND** B **OR** C.

```
A,B;C
```

But how do you represent A **AND** (B **OR** C)?

I would propose the following:
1. Continue using spaces as a delimiter.
2. **AND** each pattern on the line.
3. Fully leverage regular expressions to get the **OR**-ing functionality.

Therefore, things might look as follows:
A **OR** B

```
(A|B)
```

A **AND** B

```
A B
```

A **AND** B **OR** C

```
(A|C) (B|C)
```

A **AND** (B **OR** C)

```
A (B|C)
```

Like I said, it's not quite as pretty but I believe it gets everything you're looking for.

As for putting spaces in patterns, you would have to use the regex character class for whitespace (\s). So, 

```
new horizons -> new\shorizons
```

Let me know if that made sense or if you come up with a better way to do it.

**Comment by p-e-w** [comment]
Parsing does not have to be complex because as I said I do not intend to support arbitrary Boolean circuits. The simple rule "**AND** binds more strongly than **OR**" covers every practical use case, which is pretty much what we have already, plus the option to **AND** some patterns together (no parentheses though). By dropping some flexibility that nobody really needs (can you think of a real-world use case for a `A and (B or C)` pattern?) we can keep things minimal yet powerful.

The more I look at it the clearer it becomes that whitespace as a pattern separator is not an acceptable option. The use case `new horizons` is far too common to force people to write it as `new\shorizons`, which by the way isn't even equivalent. Look at this, however:

```
https://twitter.com/nasa new horizons,pluto;orion;iss,atv
```

Even without any instructions, it is pretty obvious what is being filtered for and what the operators mean. Yes, the comma has a special meaning in some regexes, but none of these I can see having any use for filtering news items. The guiding principle has to be to never require regular expression syntax for standard searches, which whitespace separation certainly falls under.

## 

Of course, any of this would come at the price of _some_ increase in complexity and quite a bit of additional explanation needed. Stepping back from the issue, I wonder if it is worth it at all, and indeed if per-source filters have any appreciable benefit. Please share your thoughts here, can you actually think of a common use case for these? I do want to keep krill minimal and elegant above all else and I'm not sure I am convinced of the value of this feature anymore.

**Comment by ejamesbeckham-plt** [comment]
I discovered krill and am enjoying it.  Thanks for sharing!
I do have some user feedback.
I made the mistake of trying -s"https://twitter..." -s "https://reuters/..."
I realized eventually that multiple -s switches are not handled and that all sources need to appear after a single -s.
I also made the mistake, in addition to the multiple -s switches, of having a filter / each source. -s "https://twitter/..." -f "horizons" -s"https://reuters/..." -f "greece".
I think it would be nice to support multiple -s and a -f / source.
Also, I would like a separator of some sort in the output (==== Update 2015.08.18 13:01:00 ====), for instance, so I can see what's new, faster.
I am disappointed that I cannot run it on my Mac or in native Windows.
Just my 2 cents for future features, if you continue development.
-edj

**Comment by kyokley** [comment]
@p-e-w I'm sure I could come up with some contrived example that would require a pattern like A and B or C but you're probably right in that most users aren't going to be interested. Since simplicity is a major pillar of krill, I think it makes a lot of sense to sacrifice some of the regex specification to keep things less complicated.

As for per source filtering, I think I can provide an example. Let's say I want to get updates from a twitter source (#programming) as well as something like the New York Times. Ideally, I would like to see all of the updates from NYT but only twitter posts having to do with python. Does that make sense?

**Comment by p-e-w** [comment]
@ejamesbeckham-plt: Specifying multiple URLs is standard Python `argparse` syntax and clearly documented in the README. It cannot be changed without using a different library, and having more than one parameter with the same prefix would also break 30 years of command line tradition, so that's definitely a no go. As for source-specific filters, this is indeed not supported at the moment, as discussed in this issue.

Can you elaborate a bit what you mean by separator? The output _is_ separated, by a blank line, and has every item prefixed by a date. How would you like it to look (please file a separate issue for this)?

krill _does_ run on Mac. I've tested it multiple times in the standard OS X Terminal and it worked flawlessly. If you nevertheless experience problems on Mac, please file separate issues for those.

In fact, krill even works on Windows, if you have a proper terminal emulator and a curses implementation such as that provided by Cygwin. It does not work in the Windows "command prompt", but the same is true for just about every other native *NIX program.

**Comment by p-e-w** [comment]
@kyokley: Your argument is sound. I now believe that per-source filtering can indeed provide a lot of value. I think the syntax

```
URL filter,filter;filter,filter
```

where `,` means **AND** and `;` means **OR** (and **AND** binds more strongly than **OR**), is relatively intuitive and most importantly backwards compatible with the current one.

**Comment by ejamesbeckham-plt** [comment]
I am not sure why you think multiple switches goes against 30 years of tradition.  C compilers have supported multiple -I (include path) switches FOREVER.  The idea of multiple -s switches for krill is almost exactly the same idea.
By delimiter, I mean a delimiter that indicates the LAST TIME the output of krill updated.  That is why I put a timestamp in my example.
It failed for me on Mac because some library, I think it was _curses_ something or other was not available.  I will revisit that issue.
My disappointment was with NATIVE Windows.  I know it works fine in Cygwin.

**Comment by kyokley** [comment]
@p-e-w I think I'm going to take some time and explore the **AND**/**OR** implementation some more. I guess I'm still not entirely convinced we've found the optimal solution and I'd like to put some more thought into it.

**Pull request closed without merging**
